// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-2",
    "aws_cognito_identity_pool_id": "ap-northeast-2:7796f67a-7319-464e-ade7-785a8036fbdc",
    "aws_cognito_region": "ap-northeast-2",
    "aws_user_pools_id": "ap-northeast-2_54BRdZ7n4",
    "aws_user_pools_web_client_id": "3ikdcoba6es7pl0o72170tt3ec",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://3elhrw3eezh6hfi6kgwx76sbz4.appsync-api.ap-northeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
